apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardhat-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardhat
  template:
    metadata:
      labels:
        app: hardhat
    spec:
      containers:
        - name: hardhat
          image: hardhat-node
          ports:
            - containerPort: 8545
